# Miniconda3 base
FROM continuumio/miniconda3

# The Conda environment file is copied
COPY environment.yml /tmp/environment.yml

# Install mamba for faster solves
RUN conda install -n base -c conda-forge mamba && \
    mamba env create -f /tmp/environment.yml && \
    conda clean --all --yes

# The environment will be activated by default
SHELL ["conda", "run", "-n", "exomedepth-env", "/bin/bash", "-c"]

WORKDIR /work
